# Generated by Django 5.0.4 on 2024-09-24 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='acitve',
            new_name='active',
        ),
    ]
