# Generated by Django 5.0.4 on 2024-09-27 00:13
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_tags'),
    ]

    operations = [
        TrigramExtension()
    ]
